CREATE TABLE IF NOT EXISTS `tracking`.`Users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `MacHash` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `MacHash_UNIQUE` (`MacHash` ASC))
